## input ##
input: metadata/samples.tsv

## output directory ##
outdir: ancestry_results

## resources and references ##
reference: /data1/core006/access/production/resources/reference/versions/hg19/Homo_sapiens_assembly19.fasta
kgbed: data/1000genomes_phase3_impactv7_maf0.01_snps
markers_txt: data/impactv7_and_asj_markers.txt
markers_vcf: data/impactv7_and_asj_markers.vcf
asj_markers: data/asj_marker_ids.txt
asj_marker_cutoff: 3
admix_frac_cutoff: 0.8
ignore_fams: data/1KGP_admixed_samples.fam
kgpops: data/all_phase3.new.psam
